language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - ~/.m2/repository

env:
  global:
  # GH_TOKEN
  - secure: "oghAxUq0ZQttFWHIVw+vX1WHU4DGjy/vZP8qoHwSDsiGZvsUhEqs0Vecjf0EUdNewmfjtO4pyEns5utzwUPesIN9n2Oe5SKLMyiRWR9EtxUBjBVwqXKE47fBYZS+WpqTolhYlKFKACdxahGxk54UYARZ1oHj2kbMCKBRSNig6+GbIb+KAo10+UnBSSb06WffDQ46HEn6jCZoGAuXLiIuUPM/HEHHHULzQ4Ef6oB5veci6TzwxR/BF2XGLoIqDoccdp6Pb2vxDjXHZBDewPEnwTcTTXFxPZepuDFrG6BZgHE3STK4LDg50rd66Flah7MBh+MuQYiMKhgrVuGCFSHRnE7a0OpdExGiEoUaamexqUgoE7fPMjB5s5aZwsHTUaH+Msbce379bHW0ts+qfByQdnrvxasSaalpNqPn7ZlezJE9SO5dv7Ui4rzkLA5M6BQzLm1a/84Avnn5gQ01ABzO1h/T9bfoJNiZduBo55zm3ZzFjiUG2wo0qG8VUjzSaXnkjl6Px8qV4Zo+lv2fnJcAYLQoplpvonqj/1FyCCAq2tBm3kg0PP8IVUhbtMj308bJc44etPD/DfFDC0rRYXjWrf3hSg9eVOv4deDuw7BtsQWiOBRdTACNKBfK6v3acLIMvPQv+OYplXHAMi4XxYsUvHstB+Jq7l5GtblwoWQIzQ8="
  # SONATYPE_USER
  - secure: "axonSXozZztwlwbpJdBGrx/vI3c3v9JG4Gz0KlKSn9iOpBqgX/gNWCyr18k1SG+4TEgXzD72/6ZDDnCPSYXZv5h+SKSmCkMmboxUE0KFR1hO1SOIzJtfMpv1qfIcE0ernuZIs0BuZRh35xTYjH+N7XC9HEs0LNRPjfkduiJittA="
  # SONATYPE_PASS
  - secure: "YMeNJYBhXcLJHepHzz8r0UlhZQBK33nBMQi6plaZjt/3qnJtAxVLuu6cwuycqAyuJq6vDNe+ThAVi5MZ3jNx+tpyq2x0cET6yFAUWE+9ZiI91rJFzVmY05K8zxCnMWPGmbunl/UGPGDKk0suLQxGmlrvBgRcSVONU3KuGq7lyDc="
  # GPG_KEYNAME
  - secure: "N1TK5gAnL8WWWflDSNrwghfwaN/FjqyO1DX7vCwg5sl3DpAT70E6Ju9PJ1+FXb7wF95xMzSiHVk5haOR1FxIEX2l8aP//xHtpRcAz+RM143nDs6EhmMqmD9KlimLcApkjPupn4mx8e4BFOTGqkvK7eBoIm8jWt3zKXnz4Gwy1Ko="
  # GPG_PASSPHRASE
  - secure: "gRUj21Z0K8gOGrHXj2WuH4bww3XcRZk1iScRbVdQhhTw8SFlcVhOpXoUiM68YYZABeGNJJ9XxP8QBoKKEKV5rkxAUG5+huPTdu4bwbQgHoz71awuWsrSVWXodzbT+lBxYjXkKD/AckM69olV9ZYZ5IgsFAka3geA2tPjLCO3YjE="

after_success:
#  - bash ./src/build/publish-jar.sh
  - bash ./src/build/publish-doc.sh
